version: '3.3'

networks:
  avt_wallet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  app:
    container_name: avt
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      avt_wallet:
        ipv4_address: 172.25.0.2

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '7070:3000'
    depends_on:
      - postgres
    networks:
      avt_wallet:
        ipv4_address: 172.25.0.3
        
  postgres:
    container_name: avt_wallet_postgres_db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=postgres
      - APP_DB_PASS=postgres
      - APP_DB_NAME=avt_wallet_db
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      avt_wallet:
        ipv4_address: 172.25.0.4
    restart: always

  pgadmin:
    container_name: avt_wallet_postgres_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    networks:
      avt_wallet:
        ipv4_address: 172.25.0.5
    restart: unless-stopped
