version: '3.3'

services:
  api:
    container_name: api
    image: api_avtwallet:latest
    volumes:
      - /home/thp/workspace/avtWallet-webapp/api:/workspace
    ports:
      - 7070:3000
    depends_on:
      - postgres

  postgres:
    container_name: avt_wallet_postgres_db
    image: postgres

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=admin
      - APP_DB_PASS=postgres
      - APP_DB_NAME=avt_wallet_db

    volumes:
      - ./db:/docker-entrypoint-initdb.d/

    ports:
      - 5432:5432

    restart: always

  # To manage the data base
  pgadmin:
    container_name: avt_wallet_postgres_admin

    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: 'False'

    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - 5050:80

    restart: unless-stopped

networks:
  avt_wallet_api:
    driver: bridge

volumes:
  postgres:
  pgadmin:
