import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class ValidateRecoverCodeDTO {
  @ApiProperty({
    example: 'snvoe',
  })
  @IsString()
  @IsNotEmpty()
  recoverCode: string;
}

export class ValidatedUserWithCodeDTO {
  @ApiProperty({
    example:
      'ileruhsbnflkgjshdfklgjhsdklfjhgpqoweiuqnfsjdfhlshlkjhsdflkghjklsdfg',
    description: `Token generated by the api`,
  })
  access_token: string;
}
